#!/usr/bin/env bash

# Move to the repo directory
cd /home/thomas/VTS/Hanoi-Routing/CCH-Generator || exit 1

# Make sure the build & lib directory exists
mkdir -p build lib

# Build the project
cmake -S . -B build \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_RUNTIME_OUTPUT_DIRECTORY="${PWD}/lib"

# Build the target
cmake --build build -j"$(nproc)"